### ISSUE TITLE
Unix.waitpid not working as expected on Windows?

### ISSUE THREAD

**Issue by dra27** [janestreet/jbuilder#101]
```
OPAM+DRA@OPAM /cygdrive/c/DRA/opam/src/format
$ jbuilder.exe build opam_format.cma
      ocamlc opamSwitch.{cmi,cmti} (exit 2)
(cd _build/default && C:\DRA\opam\bootstrap\bin\ocamlc.opt.exe -w -40 -g -bin-annot -no-alias-deps -I . -o opamSwitch.cmi -c -intf opamSwitch.mli)
File "opamSwitch.mli", line 14, characters 8-24:
Error: Unbound module OpamStd
Fatal error: exception Unix.Unix_error(3, "waitpid", "")
Called from file "src/future.ml", line 544, characters 6-33
Called from file "pervasives.ml", line 482, characters 30-33
Called from file "pervasives.ml", line 487, characters 2-15
Called from file "bin/main.ml", line 815, characters 4-10
```
The error in my file is correct - it's the `Unix_error` which I'm wondering about. I have made no investigation, but I wonder if it's either related to fake PIDs used in Unix (see https://github.com/dra27/opam/commit/7451c127d12ed2f0eee92ca99f2a2d052af75b0b) or a use of a group parameter to waitpid (related to https://github.com/dra27/opam/commit/38c3a9fb67718076d7a293f9bce53b848030959d)?

**Comment by diml** [comment]
It's a race condition in the code, it ends up calling Unix.waitpid after the process has exited, I'll fix it

**Comment by diml** [comment]
I cleaned the code, it should be fine now
