### ISSUE TITLE
jbuilder appears to buffer runtest output

### ISSUE THREAD

**Issue by andrewray** [janestreet/jbuilder#107]
I have a test which is hanging, however, I dont see any test output from jbuilder, which makes it difficult to track down the problem.

In fact, it doesn't even show that the test has started, so initially, I thought jbuilder itself was hanging.

Normally this wouldn't be an issue, as I can run the test by hand, but the test only fails on Travis in this case.

**Comment by diml** [comment]
Yh, basically jbuilder captures the output of all sub-commands to avoid interleaving when multiple commands are executed in parallel and also to dump their output in the log file. It also print commands after they have finished by default to provide a better output. If you run with `-verbose`, you will see the command printed at the time it is being executed.

I guess they could be an option to not capture the output.

**Comment by andrewray** [comment]
Thanks - verbose will do the trick here, especially since the JOBS=1 on travis.

**Comment by diml** [comment]
Ok. In any case this has already been requested so I think it's worth added. I added a `--no-buffer` option
