### ISSUE TITLE
Subdirectory compilation

### ISSUE THREAD

**Issue by Freyr666** [janestreet/jbuilder#109]
I have a source code tree such as:

```
├── jbuild
├── a.ml
├── b.ml
└── subdir
      └── c.ml
```

where `c.ml` depends on `b.ml`, a `a.ml` depends on `c.ml`. Reading the jbuilder documentation I can't understand how to write a `jbuild` file for this case.

**Comment by diml** [comment]
Jbuilder requires all the .ml/.mli files to be in the same directory as the jbuild. However, these files can be generated. Especially this mean that you can setup a rule to copy c.ml to the parent directory.

If you have a lot of files this will be cumbersome. However #35 will add a new stanza to make this easier:

```scheme
(copy_files# subdir/*.{ml,mli})
```

**Comment by Freyr666** [comment]
>Especially this mean that you can setup a rule to copy c.ml to the parent directory.

This looks a little bit complex (especially in case of greater levels of nesting). Have you any plans on a more decent subdirectory support? In particular many modern languages (like clojure for example) support namespaces dictated by the file system (e.g. functions in `api/file.clj` would have `api.file.` namespace). Could it be achieved on a build system level and what do you think of it? I've heard many complains on how OCaml ignores FS hierarchy.

**Comment by diml** [comment]
Currently OCaml doesn't support namespacing. Jbuilder implements poor man namespacing for libraries using module aliases. This works for now but is not ideal. Jbuilder could try to do the same to support FS hierarchy but that would become very complicated and fragile.

There are ideas to add proper support for namespacing in OCaml and support FS hierarchy. When this lands, Jbuilder will support it. In the meantime copying files is the best you can do.

**Comment by Freyr666** [comment]
@diml Ok, so for now I should copy files one by one manually? Is there any way to copy all directory content in once?

**Comment by diml** [comment]
Until #35 lands, yh you have to copy files one by one

**Comment by Freyr666** [comment]
Ok, thanks for reply.

**Comment by TheSpyder** [comment]
I addressed this by creating a `jbuild` file defining a `(wrapped false)` library in each subfolder, but I came here to complain because that is cumbersome and makes shared properties like the compiler warning list more annoying. Depending on how many folders vs files are in the project though, the library approach might be easier than a copy rule for each file.

`copy_files` seems to do what I'm after, which is let jbuilder match the source layout of other ocaml build tools I've used. Their flexibility with subfolders is how I ended up with a project structure that has them in the first place :)

**Comment by rgrinberg** [comment]
The latest release now supports `copy_files`. Please re-open if you still have any other concerns.

**Comment by TheSpyder** [comment]
works great, thanks 👍

**Comment by TheSpyder** [comment]
It's taken me a while to realise it was the fault of this change, but it breaks paths in error messages. Compile errors now print the location of the file inside _build after `copy_files` has run, not the original file.

This makes sense thinking about the implementation, but it means my editor console regex to locate errors is completely broken. Merlin is great, but still I use console analysis of my build task for some things.

**Comment by rgrinberg** [comment]
Hi Andrew,

Make sure that you’re using copy_files# rather than copy_files. The former
will add the necessary lines mapping errors to the original code.

**Comment by TheSpyder** [comment]
oh, thanks! I didn't really understand the difference at the time but that makes sense.

It was a little complicated because the line directive isn't valid for `mll` or `mly` files, but it's working now 👍
