### ISSUE TITLE
doc for subst

### ISSUE THREAD

**Issue by samoht** [janestreet/jbuilder#115]
The doc for `jbuilder subst --help` is wrong, it says to add:

```
 ["jbuilder" "subst" name] {pinned}
```

which is not a valid command (I guess a `-n` is missing). Also there is no doc about it in the manual. Would be great to explain what substitution it does (by default, and maybe if there is a way to add custom ones)

**Comment by diml** [comment]
Indeed, I updated the doc

**Comment by samoht** [comment]
Thanks!

Also http://jbuilder.readthedocs.io/en/latest/search.html?q=subst&check_keywords=yes&area=default doens't return any result. Would be great to add a section about that command there too :-)

**Comment by diml** [comment]
Indeed, I added some doc
