### ISSUE TITLE
Two .cmxa libraries of the same name that belong to different packages

### ISSUE THREAD

**Issue by dkim** [janestreet/jbuilder#118]
jbuilder appears not to work well in a corner case where two `.cmxa` libraries belonging to different packages happen to have the same name. For instance, two OPAM packages, [ctypes](https://opam.ocaml.org/packages/ctypes/) and [ctypes-build](https://opam.ocaml.org/packages/ctypes-build/), happen to install their respective libraries under the same filename `ctypes.cmxa`:

```bash
$ ls ~/.opam/4.04.1/lib/ctypes/ctypes.cmxa
/Users/foo/.opam/4.04.1/lib/ctypes/ctypes.cmxa

$ ls ~/.opam/4.04.1/lib/ctypes-build/ctypes.cmxa
/Users/foo/.opam/4.04.1/lib/ctypes-build/ctypes.cmxa
```

jbuilder fails with an error as follows when it needs to link object files with both of those `ctypes.cmxa`:

```bash
$ jbuilder build generator.exe
    ocamldep generator.depends.ocamldep-output
      ocamlc bindings.{cmi,cmo,cmt}
      ocamlc generator.{cmi,cmo,cmt}
    ocamlopt bindings.{cmx,o}
    ocamlopt generator.{cmx,o}
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Ctypes_stub_generator, and 
its interface was not compiled with -opaque
    ocamlopt generator.exe (exit 2)
(cd _build/default && /Users/foo/.opam/4.04.1/bin/ocamlopt.opt -w -40 -g -o generator.exe
-I /Users/foo/.opam/4.04.1/lib/bytes
-I /Users/foo/.opam/4.04.1/lib/ctypes
-I /Users/foo/.opam/4.04.1/lib/ctypes-build
-I /Users/foo/.opam/4.04.1/lib/integers
-I /Users/foo/.opam/4.04.1/lib/ocaml
unix.cmxa bigarray.cmxa str.cmxa integers.cmxa 
ctypes.cmxa
cstubs.cmxa
ctypes.cmxa
bindings.cmx generator.cmx)
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Ctypes_stub_generator referenced from generator.cmx
```

The cause of the trouble is that jbuilder uses the names of `.cmxa` libraries with `-I` options, instead of their full paths, when it assembles a command line to execute. Note that there were two occurrences of `ctypes.cmxa` in the command line shown above (`(cd _build/default && ... generator.cmx)`) and that `-I .../ctypes` preceded `-I .../ctypes-build`. The OCaml compiler associates the second occurrence of `ctypes.cmxa` with `ctypes.cmxa` in `.../ctypes`, not the intended one in `.../ctypes-build`, because it searches `-I` directories in the order in which they were given on the command line. The compilation finished successfully when experimentally given the full paths of `ctypes.cmxa`:

```bash
$ (cd _build/default && /Users/foo/.opam/4.04.1/bin/ocamlopt.opt -w -40 -g -o generator.exe
-I /Users/foo/.opam/4.04.1/lib/bytes
-I /Users/foo/.opam/4.04.1/lib/ctypes
-I /Users/foo/.opam/4.04.1/lib/ctypes-build
-I /Users/foo/.opam/4.04.1/lib/integers
-I /Users/foo/.opam/4.04.1/lib/ocaml
unix.cmxa bigarray.cmxa str.cmxa integers.cmxa
/Users/foo/.opam/4.04.1/lib/ctypes/ctypes.cmxa
cstubs.cmxa
/Users/foo/.opam/4.04.1/lib/ctypes-build/ctypes.cmxa
bindings.cmx generator.cmx)

$ ls _build/default/generator.exe
_build/default/generator.exe
```

Below is code that reproduces the problem:

```bash
$ ls
bindings.ml  generator.ml jbuild

$ cat jbuild
(executable
  ((name generator)
   (libraries (ctypes-build.stub-generator))))

$ cat generator.ml
let () =
  let configs = Ctypes_stub_generator.[
      {name = "foo";
       errno = Cstubs.ignore_errno;
       concurrency = Cstubs.sequential;
       headers = "";
       bindings = (module Bindings.B)}
  ] in
  Ctypes_stub_generator.main configs

$ cat bindings.ml
open Ctypes
module B (F : Cstubs.FOREIGN) = struct
  open! F
  let abs = foreign "abs" (int @-> returning int)
end

$ jbuilder build generator.exe
```

**Comment by dkim** [comment]
This name clash does not arise anymore with the development version of ctypes-build because its `ctypes.cmxa` has been [renamed](https://github.com/yallop/ocaml-ctypes-build/pull/9) to `ctypes-build.cmxa`. Thank you, @yallop!

However, I will leave this issue open because this problem may still be encountered with a combination of some other packages.

**Comment by diml** [comment]
Basically the rationale for using the basename is that you need the `-I` anyway for stubs, so we might as well make the command line shorter.

In general the archives are named after the library name, which must be unique. So I don't think fixing this problem is high priority.

**Comment by dkim** [comment]
I agree that this is a rare instance. Do you want this issue to be closed or to be kept for future reference? Anyway, thank you for checking this issue.

**Comment by diml** [comment]
Let's keep it open for future reference
