### ISSUE TITLE
building .cmxa does not build/link c_names files

### ISSUE THREAD

**Issue by lehy-probayes** [janestreet/jbuilder#131]
Consider the following setup:
```#!/bin/bash
echo "This C file does not compile" > exists.c
echo "let x = 42" > a.ml
cat << EOF > jbuild
(jbuild_version 1)
(library
 ((name            mylib)
  (modules         (a))
  (c_names         (exists doesnotexist))
))
EOF
```
Note that one of the C files exists but contains code that does not compile, and  the other does not exist.
Then:
```jbuilder build mylib.cmxa --verbose```
-> builds mylib.cmxa without building exists.c and doesnotexist.c. This links against a libmylib_stubs.a which is not built and does not exist anywhere AFAICS:
```
Running[2]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamldep.opt -modules a.ml -impl mylib.ml-gen) > _build/default/mylib.depends.ocamldep-output
Running[3]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlc.opt -w -40 -w -49 -g -bin-annot -no-alias-deps -I . -o mylib.cmo -c -impl mylib.ml-gen)
Running[4]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -w -49 -g -intf-suffix .ml-gen -no-alias-deps -I . -o mylib.cmx -c -impl mylib.ml-gen)
Running[5]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlc.opt -w -40 -g -bin-annot -no-alias-deps -I . -open Mylib -o mylib__A.cmo -c -impl a.ml)
Running[6]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -g -intf-suffix .ml -no-alias-deps -I . -open Mylib -o mylib__A.cmx -c -impl a.ml)
Running[7]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -g -a -o mylib.cmxa -cclib -lmylib_stubs mylib.cmx mylib__A.cmx)
```
However, if I ask for the .cmxs, the .cmxa is correctly built with the C files inside (I fixed up exists.c and touched doesnotexist.c):
```jbuilder build mylib.cmxs --verbose```

```
Running[2]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlc.opt -g -ccopt -g -o doesnotexist.o doesnotexist.c)
Running[3]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlc.opt -g -ccopt -g -o exists.o exists.c)
Running[4]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamldep.opt -modules a.ml -impl mylib.ml-gen) > _build/default/mylib.depends.ocamldep-output
Running[5]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlc.opt -w -40 -w -49 -g -bin-annot -no-alias-deps -I . -o mylib.cmo -c -impl mylib.ml-gen)
Running[6]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -w -49 -g -intf-suffix .ml-gen -no-alias-deps -I . -o mylib.cmx -c -impl mylib.ml-gen)
Running[7]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlc.opt -w -40 -g -bin-annot -no-alias-deps -I . -open Mylib -o mylib__A.cmo -c -impl a.ml)
Running[8]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -g -intf-suffix .ml -no-alias-deps -I . -open Mylib -o mylib__A.cmx -c -impl a.ml)
Running[9]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -g -a -o mylib.cmxa -cclib -lmylib_stubs mylib.cmx mylib__A.cmx)
Running[10]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlmklib.opt -g -o mylib_stubs exists.o doesnotexist.o)
Running[11]: (cd _build/default && /home/rlehy/.opam/4.04.0/bin/ocamlopt.opt -w -40 -g -shared -linkall -I . -o mylib.cmxs mylib.cmxa)
```

**Comment by diml** [comment]
Yes, that's the expected behavior. Since in practice you don't need the .a to build the .cmxa, not declaring such a dependency improves parallelism.

In general one builds the `@install` alias by default, which depends on everything to be installed. Why doesn't that work in your case?

**Comment by lehy** [comment]
OK, thank you. Just a few explanations about why I am doing this.

I did not make a package at this point and am just building things like I read in the "quickstart / building a hello world program" section of the doc, by passing the target I want. I am afraid there is something fundamental that I don't understand (not your problem, I should probably reread things about the OCaml build process), since it seems to me that if I ask a library to include C files, I expect everything needed to be built to have the library work (including the C code), rather than ignore silently my `c_names`.

Also, I am trying to generate bindings using cstubs, which is rather convoluted, and I am building things step by step to debug my build.

Finally, I am interested in generating the .cma (which fails to include my C files, like the .cmxa show above) in order to load it into the toplevel and test interactively (using #load manually).

Also, even more finally, most of the time when I develop I never install things in general, unless everything is working and I am creating a package. I build and run the tests. Should I install more :) ?

(I am still confused why linking with a non-existent lib (-lmylib_stubs) succeeds though. However this probably has little to see with jbuilder?)

Thanks again!

**Comment by diml** [comment]
Hmm, there is indeed something missing in jbuilder for this. I think we need a target, in the form of an alias to build all the artifacts for a library, and probably all the dependencies as well. Alternatively, would #114 be enough? This is how it would work:

```
$ ls
jbuild
foo.mli
foo.ml
$ jbuilder top
<jbuilder builds some stuff>
    OCaml 4.04.1

# Foo.f;;
val f : int -> int
```

i.e. running `jbuilder top` in a directory would drop a toplevel with all the libraries in the current folder ready for interactive use.

> Also, I am trying to generate bindings using cstubs, which is rather convoluted, and I am building things step by step to debug my build.

cstubs as in ctypes? I think we should just add the ctypes rules to jbuilder directly. It makes sense for jbuilder to support this officially.

> (I am still confused why linking with a non-existent lib (-lmylib_stubs) succeeds though. However this probably has little to see with jbuilder?)

Well, linking an executable would definitely fail, but for a library it's fine in general.

**Comment by lehy-probayes** [comment]
All of this (the alias to build all the artifacts for a library, jbuilder top, and a rule for ctypes.stubs) would obviously be awesome. Anyway thanks to your explanations I can make my thing work right now. Whatever the small difficulties, jbuilder is already making my life easier; thanks again.

**Comment by dkim** [comment]
AFAIK, `ocamlopt` just recorded the `-cclib -lmylib_stubs` option in the resulting `mylib.cmxa` library because the `-cclib` option was given along with the `-a` option. From the man page for `ocamlopt`:

```
-a     ...
       If -cclib or -ccopt options are  passed  on  the  command  line,
       these  options are stored in the resulting .cmxa library.  Then,
       linking  with  this  library   automatically   adds   back   the
       -cclib and -ccopt  options  as  if they had been provided on the
       command line, unless the -noautolink option is given.  Addition-
       ally,  a  substring $CAMLORIGIN inside a  -ccopt options will be
       replaced by the full path to the  .cma  library,  excluding  the
       filename.
```
