### ISSUE TITLE
inferred rule doesn't parse

### ISSUE THREAD

**Issue by agarwal** [janestreet/jbuilder#132]
The [inferred rules](http://jbuilder.readthedocs.io/en/latest/jbuild.html#inferred-rules) section of the manual describes the syntax `(rule (copy a b))`. When I try this, it doesn't parse.

```
$ cat jbuild
(jbuild_version 1)
(rule (copy a b))

$ jbuilder build
File "jbuild", line 2, characters 7-11:
Error: S-expression of the form (_ _) expected
```

**Comment by diml** [comment]
What version of jbuilder are you using? They were added recently, you need jbuilder >= 1.0+beta10 (https://github.com/ocaml/opam-repository/pull/9449)

**Comment by agarwal** [comment]
```
$ jbuilder --version
1.0+beta9
```

**Comment by agarwal** [comment]
So I'll upgrade.
