### ISSUE TITLE
Jbuilder not building bytecode and native executable at the same time

### ISSUE THREAD

**Issue by bikalgurung** [janestreet/jbuilder#139]
My jbuild is as follows
```
$ cat jbuild 
(jbuild version 1)
(executable 
  ((name   hello)
    (public_name hello)
    (modes   (byte native))
    (flags (:standard -safe-string))))

$ cat hello.ml
let () =
   print_string "hello world\n"

$ cat hello.opam
opam-version: "1.2"
build: [
     ["jbuilder" "build" "--only-packages=odocopt" "--root" "." "-j" jobs "@install"]
]

depends: [
  "jbuilder"        {build & >= "1.0+beta8"}
```
However, executing command `jbuilder build` only builds `hello.exe` and not `hello.bc`. Shouldn't having `(modes (byte native)` create both `hello.exe` and `hello.bc` in the same `jbuilder build` invocation? I can generate `hello.bc` but only after removing `native` from the `modes` list. 

The manual seems to suggest this is the expected functionality, i.e. when there is `(modes (byte native)` jbuilder will build both and not favor native at the expense of byte.

**Comment by dra27** [comment]
If you look at the .install file generated, I think you'll find that it's only installing `hello.exe`? If you want `jbuilder build [@install]` to build hello.bc as well, I'm fairly sure you need to add an `install` stanza to your jbuild file.

**Comment by diml** [comment]
Basically `(modes ...)` is used to describe what can be built. Maybe the doc is not very clear. The idea is that if you write `(modes (byte))` then jbuilder will not try to build the native version and will fallback to the byte-code version.

Regarding building both at once, you can ask for it explicitely:

```
$ jbuilder build hello.{exe,bc}
```

The `@install` target will build only things that are to be installed and only one of the native or byte-code version gets installed for executables. If you want to install both, you indeed need to add an `install` stanza.

**Comment by bikalgurung** [comment]
> `$ jbuilder build hello.{exe,bc}`

Exactly what I was looking for. Thanks. 👍
