### ISSUE TITLE
Windows fixes

### ISSUE THREAD

**Issue by samoht** [janestreet/jbuilder#146]
Not sure if you saw but @fdopen has a patch on jbuilder to make it work on Windows/Cygwin:

https://github.com/fdopen/opam-repository-mingw/blob/master/packages/jbuilder/jbuilder.1.0%2Bbeta10/files/jbuilder-1.0%2Bbeta10.patch

**Comment by dra27** [comment]
Thanks - I'll review that later (it looks fine, though I'm surprised at not having hit problems with the ocaml.exe one)

**Comment by dra27** [comment]
Thanks @samoht for highlighting the patch and @fdopen for finding the bugs - this is now in #147.
