### ISSUE TITLE
Question about bistring.syntax and jbuilder

### ISSUE THREAD

**Issue by dakk** [janestreet/jbuilder#151]
Hi, I think this is just a question, but it could be a problem of jbuild.
I'm starting my first project using jbuilder; in my code I use the bitstring syntax extension from the bitstring package. When I try to make the project, jbuild fails on lines which uses the bitstring syntax:

For example it fails here on the first line with a syntax error.
```ocaml
let bs = BITSTRING {
	h.version 					: 4*8 : littleendian;
	Hash.to_bin h.prev_block		: 32*8: string; 
	Hash.to_bin h.merkle_root	: 32*8: string;
	btime					: 32 : string;
	bbits						: 32 : string;
	bnonce					: 32 : string
} 
```

The project compiles fine with oasis (I'm migrating from oasis to jbuilder).

This is my jbuild:

```ocaml
(jbuild_version 1)

(library
 ((name        bitcoinml)
  (public_name bitcoinml)
  (libraries (bitstring.syntax bitstring stdint))))
```

This is my opam depends

```ocaml
depends: [
  "jbuilder" {build & >= "1.0+beta9"}
  "base" {build & >= "v0.9.2"}
  "stdio" {build & >= "v0.9.0"}
  "configurator" {build & >= "v0.9.1"}
  "bitstring" {build & >= "2.1.0"}
  "stdint" {build & >= "0.3.0-0"}
  "ounit" {test & >= "2.2.2"}
]
```

Am I missing something?

**Comment by diml** [comment]
bitstring.syntax is a camlp4 syntax extension and there is no built-in support for those. You can use them with jbuilder with a bit of work, but i would recommend switching to  ppx_bitstring, since camlp4 is deprecated.

**Comment by dakk** [comment]
I never studied in depth syntax extension world; thank you for your reply, now the problem is clear
