### ISSUE TITLE
a non compiling .ml file in the directory is problematic

### ISSUE THREAD

**Issue by UnixJunkie** [janestreet/jbuilder#162]
Apparently, if a non compiling .ml file is present, this prevents jbuilder from finishing successfuly, even if the file is not needed to build what was asked.
That looks a little bit overzealous.

**Comment by UnixJunkie** [comment]
ocamldep codec.depends.ocamldep-output (exit 2)
(cd _build/default && /home/berenger/.opam/4.04.1/bin/ocamldep.opt -modules ac.ml atom.ml attic.ml bbox.ml bild.ml codec.ml color.ml flags.ml molecule.ml myArray.ml par_work.ml plr.ml pqr.ml score.ml utls.ml weight.ml) > _build/default/codec.depends.ocamldep-output
File "attic.ml", line 31, characters 0-3:
Error: Syntax error

**Comment by rgrinberg** [comment]
You can specify the sources explicitly for your library with `(modules (x y z))`

**Comment by samoht** [comment]
Or `(modules (:standard \ attic))` as specified in the docs :-)

**Comment by rgrinberg** [comment]
I think the comments here are enough to workaround your issue, so I'm closing. Feel free to ask more questions @UnixJunkie
