### ISSUE TITLE
The deprecated-ppx-method wrapper does not forward PPX options

### ISSUE THREAD

**Issue by aantron** [janestreet/jbuilder#163]
For a PPX, Jbuilder [generates two packages in `META`](https://github.com/ocsigen/lwt/blob/cc98e5f09383a6a465d3aa9620ddf2d46eb16075/META.lwt.template#L26-L52): `ppx_foo`, to be used by a PPX driver, and `ppx_foo.deprecated-ppx-method`, for old-style non-PPX-driver usage. `ppx_foo` pulls in `ppx_foo.deprecated-ppx-method` automatically when not running under a PPX driver. This is a nice feature, because both users that are using Jbuilder/PPX drivers, and users that are expecting an old-style PPX, can refer to the PPX as `ppx_foo`.

However, the latter users cannot pass options to `ppx_foo`: they have to pass the options to `ppx_foo.deprecated-ppx-method`, despite that this scheme seems intended to hide this distinction from them.

Not having this quirk would help the teachability of package interfaces.

From https://github.com/aantron/bisect_ppx/pull/117#issuecomment-310558775:

> ```
> Passing ppxopts used to be done with ocamlfind by
>
>   -package bisect_ppx -ppxopt bisect_ppx,your_opts
>
> with the bisect_ppx.deprecated-ppx-method scheme, it apparently has to
> be, at least for now,
>
>   -package bisect_ppx -ppxopt bisect_ppx.deprecated-ppx-method,your_opts
> ```

**Comment by aantron** [comment]
I seem to have fixed the issue by inverting the packaging: instead of `ppx_foo` being the OMP backage and `ppx_foo.deprecated-ppx-method` for old-style PPX, I made `ppx_foo` the old-style PPX, and created `ppx_foo.omp`, which is pulled in by `ppx_foo` on predicate `ppx_driver`:

```
version = "dev"
description = "Code coverage for OCaml"
requires(ppx_driver) = "bisect_ppx.omp"
requires(-ppx_driver) = "bisect_ppx.runtime"
ppx(-ppx_driver,-custom_ppx) = "./ppx.exe --as-ppx"

package "omp" (
  version = "dev"
  description = "Bisect_ppx ocaml-migrate-parsetree PPX (internal)"
  requires = "bigarray
              bisect_ppx.runtime
              compiler-libs
              compiler-libs.common
              ocaml-migrate-parsetree
              ppx_tools_versioned
              ppx_tools_versioned.metaquot_404
              str
              unix"
  ppx_runtime_deps = "bisect_ppx.runtime"
  archive(byte) = "bisect_ppx.cma"
  archive(native) = "bisect_ppx.cmxa"
  plugin(byte) = "bisect_ppx.cma"
  plugin(native) = "bisect_ppx.cmxs"
)
```

It appears to work fine with PPX options in Jbuilder, ocamlfind, and Ocamlbuild. In all cases, the package can be named as `bisect_ppx`.

If this is not overlooking anything, I would suggest emitting this method in the generated `META`, instead of the `deprecated-ppx-method` approach.

**Comment by aantron** [comment]
Looking harder at it, I'm not sure two packages are even required (cc @let-def, @Drup). It looks like everything could be [achieved with one package and predicates](https://github.com/let-def/ocaml-migrate-parsetree/blob/master/examples/omp_ppx_here/META) (thanks @let-def for examples). Are the two separate packages required by Jbuilder somehow?

**Comment by diml** [comment]
It's possible that you could do everything with a single findlib package. That's what I tried initially for Jane Street packages (this was before jbuilder). There are some annoying corner cases and using two packages was easier to think about. I described the various use cases here: https://github.com/janestreet/ppx_driver#ppx_driver-rewriters-as-findlib-libraries. If we can find a scheme that cover all cases with a single findlib package I'm happy to switch to it

**Comment by diml** [comment]
Looking at this again, it seems to me that we can simply inline the fields of the sub-package, I prepared a PR
