### ISSUE TITLE
Option to automatically install missing dependencies via opam

### ISSUE THREAD

**Issue by bobbypriambodo** [janestreet/jbuilder#164]
As we already have `jbuilder external-lib-deps --missing @install` command to print out missing dependencies along with a hint to install, is it possible to (perhaps through another option flag, e.g. `--install-missing`) automatically install those missing dependencies via opam? Is it out of jbuilder's scope? Or does the feature already exist (I can't seem to find it in the docs)?

I'm thinking it could improve the workflow to start working on a project, one less command to type, and it would be more automation-friendly. One issue that I could think of is how to handle `opam depext` as it might be too intrusive to install OS packages, but I'm not sure if that's a deal-breaker.

**Comment by hakuch** [comment]
I usually do this with `opam install NAME --deps-only`. Do you mean that you'd prefer to be able to do this from `jbuilder`?

**Comment by bobbypriambodo** [comment]
I'm not sure, what goes in `NAME`?

My use case is this: suppose I have a project for an executable named `foo` which depends on libraries, say, `lib1 lib2 lib3` as stated in the `jbuild` file, and I don't have `lib1`, `lib2`, and `lib3` installed on my current switch. As it is, running `jbuilder build @install` would fail, and `jbuilder external-lib-deps --missing @install` will print out the three libs as missing dependencies.

I can of course do `opam install lib1 lib2 lib3`, but I'm thinking of a feature/command where I could install all the missing dependencies _without explicitly specifying their names_ (because jbuilder can already infer them anyway, and I can see it become unwieldy if the deps list is long enough).

However, I'm still not sure whether this is a good idea or if there is already a proper way to do this.

**Comment by hakuch** [comment]
@bobbypriambodo, `NAME` would be the name of the project that you're building.

So if you you're building the `mypkg` project, with `mypkg.opam`, then `opam install mypkg --only-deps` will install all dependencies of `mypkg` with `opam`.

**Comment by rgrinberg** [comment]
The issue with making this work is that the dependencies jbuilder reports are missing aren't necessarily opam dependencies. Those are findlib dependencies which may not necessarily match opam names.

I'd second @hakuch suggestion but improve it to:

```
$ opam install --deps-only .
```

If you have opam 2.0

**Comment by bobbypriambodo** [comment]
Ah, I see now. After @hakuch's reply I tried `opam install <mypackage> --deps-only` and it failed, but it turns out that I just need to pin the package first for the command to work. Still familiarizing myself with the workflow. @rgrinberg your suggestion looks cool but I'm still using opam 1.2.2 for now. 2.0 seems awesome (local switches!) and I can't wait until it's out of beta.

> The issue with making this work is that the dependencies jbuilder reports are missing aren't necessarily opam dependencies. Those are findlib dependencies which may not necessarily match opam names.

I see, I didn't know that. But there is a hint to install via opam, so I'm guessing there's a way to differentiate them?

Either way, I realize that opam already handles my particular use case and I think there is no need for jbuilder to implement it, therefore I'm taking the liberty to close this issue. @hakuch @rgrinberg really appreciate your help!

**Comment by anentropic** [comment]
For any other noobs like me searching for how to do this (I could not find it after a few skims through the Dune docs)...

I have a fresh install of OCaml and opam (via Homebrew) and I have a dune project I've been working on.

I have a `myproject.opam` file in the root of my project, which is auto-generated by dune based on my `dune-project` file.

Say I check out my project src code on a new machine. I want to install all the deps at once.

I'm in the root of my project. If I do `opam install myproject --deps-only` I get `No package named myproject found.`

What does work instead is `opam install ./ --deps-only`

**Comment by bbatsov** [comment]
> I'm in the root of my project. If I do opam install myproject --deps-only I get No package named myproject found.

Yeah, this took me a while to figure out as well. Most build tools would have some way to install a project's deps or at the very least they wouldn't require a step to generate the manifest needed to install them. I think there's a lot of potential to make this behavior simpler for newcomer to OCaml/Dune.

**Comment by Et7f3** [comment]
The broader issue is that dune is a build system. It can be used with different package manager: native package manager (pacman, apt, nix), opam or esy. esy and nix does sandboxing and nix forbid network access. One tools that emerge from this status quo is https://github.com/OCamlPro/drom so it is both package manager and build tools

**Comment by bbatsov** [comment]
Yeah, I understand the broader issue, but it still seems to me things can be done differently. Haven't thought much about the issue, but at the very least this should be covered more extensively in the docs.

**Comment by bbatsov** [comment]
To be more specific:

- I find it weird that issue and a topic on SO are the top results when you google for "install dependencies for a dune project" 
- Dune's docs have only this https://dune.readthedocs.io/en/stable/opam.html, which is kind of vague if you ask me
- I couldn't find any meaningful overview of the deps situations when searching for "dependencies" in the Dune's docs

Perhaps I'm just too used to build tools like Gradle, Maven, Leiningen, etc But my guess is that the most people coming to OCaml from other languages are going to face the same problem.

**Comment by anentropic** [comment]
> What does work instead is `opam install ./ --deps-only`

this doesn't seem to install `with-test` deps though... is there a way to get those too?
