### ISSUE TITLE
jbuilder clean appears to leave .merlin files

### ISSUE THREAD

**Issue by aantron** [janestreet/jbuilder#166]
E.g., in Lwt:

```
λ jbuilder clean
λ find . -name '*.merlin'
./src/core/.merlin
./src/logger/.merlin
./src/ppx/.merlin
./src/preemptive/.merlin
./src/react/.merlin
./src/simple_top/.merlin
./src/unix/.merlin
./src/unix/config/.merlin
./src/unix/stubs/.merlin
./test/.merlin
./test/core/.merlin
./test/ppx/.merlin
./test/preemptive/.merlin
./test/react/.merlin
./test/unix/.merlin
```

At least from reading #89 and the `clean` command docs, I got the impression that they should be removed.

```
DESCRIPTION
       Removes files added by jbuilder such as _build, <package>.install, and
       .merlin
```

cc @rdavison

**Comment by diml** [comment]
Basically jbuilder removes the .merlin files it created itself. If you remove the `_build` directory it won't know which ones to delete for instance. Do you have a sequence of commands to reproduce this from a clean checkout?

**Comment by aantron** [comment]
You're right, this was the result of some weird sequence of commands in Lwt. Apologies for the incorrect issue.
