### ISSUE TITLE
jbuilder rules doesn't work when odoc is missing

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#170]
For example:
```
 [rgrinberg:~/reps/ml/ocaml-cohttp] master 1 ± jbuilder rules
Error: Program odoc not found in the tree or in PATH (context: default)
Hint: opam install odoc
```

**Comment by mseri** [comment]
Also if `js_of_ocaml` is missing. Same kind of error

**Comment by diml** [comment]
Indeed, currently executables are resolved eagerly. We could change the type of programs from in actions from `Path.t` to `type t = This of Path.t | Not_found of string` so that we fail only when executing the action.

**Comment by rgrinberg** [comment]
#292 tries to address this.
