### ISSUE TITLE
failure to compile when depending on ocamlnet

### ISSUE THREAD

**Issue by UnixJunkie** [janestreet/jbuilder#177]
ocamlopt src/codec.exe (exit 2)
    (cd _build/default && /home/berenger/.opam/4.04.1/bin/ocamlopt.opt -w -40 -g -o src/codec.exe -I /home/berenger/.opam/4.04.1/lib/batteries -I /home/berenger/.opam/4.04.1/lib/bytes -I /home/berenger/.opam/4.04.1/lib/cpm -I /home/berenger/.opam/4.04.1/lib/dolog -I /home/berenger/.opam/4.04.1/lib/genspir -I /home/berenger/.opam/4.04.1/lib/netcamlbox -I /home/berenger/.opam/4.04.1/lib/netsys -I /home/berenger/.opam/4.04.1/lib/num -I /home/berenger/.opam/4.04.1/lib/ocaml -I /home/berenger/.opam/4.04.1/lib/ocaml/threads -I /home/berenger/.opam/4.04.1/lib/parany -I /home/berenger/.opam/4.04.1/lib/parmap -I /home/berenger/.opam/4.04.1/lib/vector3 -I /home/berenger/.opam/4.04.1/lib/zip nums.cmxa unix.cmxa threads.cmxa bigarray.cmxa str.cmxa batteries.cmxa batteriesThread.cmxa netsys_oothr_mt.cmxa netsys_oothr_mt_init.cmx netsys.cmxa netsys_c_outofheap.o netcamlbox.cmxa dolog.cmxa parmap.cmxa vector3.cmxa cpm.cmxa genspir.cmxa zip.cmxa parany.cmxa src/utls.cmx src/atom.cmx src/myFloat.cmx src/dist_weight.cmx src/flags.cmx src/molecule.cmx src/myArray.cmx src/score.cmx src/ac.cmx src/color.cmx src/plr.cmx src/pqr.cmx src/codec.cmx)
    gcc: error: netsys_c_outofheap.o: No such file or directory
    File "caml_startup", line 1:
    Error: Error during linking

**Comment by UnixJunkie** [comment]
(jbuild_version 1)

    (executable
     ((name codec)
      (libraries (batteries dolog parmap str vector3 cpm genspir zip parany))))

**Comment by UnixJunkie** [comment]
parany uses ocamlnet. If I remove it (the exe is not yet using it) then it compiles fine.

**Comment by UnixJunkie** [comment]
this builds fine in case oasis is used (and driving ocamlbuild)

**Comment by UnixJunkie** [comment]
I think this can be closed since the corresponding fix was merged.
I wouldn't mind a new minor release in opam by the way, since it was a bugfix.

**Comment by diml** [comment]
I'm hoping to do the 1.0.0 release soon, but we'll do another bugfix release if it takes too long

**Comment by rgrinberg** [comment]
1.0+beta12 fixes this
