### ISSUE TITLE
Parser generators and dependencies with .ml{,y,i} files.

### ISSUE THREAD

**Issue by jnfoster** [janestreet/jbuilder#187]
If I manually run Menhir in my source directory, it generates `.ml` and `.mli` files. If I forget to delete those files and then run `jbuilder` it will ignore subsequent changes to the `.mly` file, which can be very confusing.

**Comment by diml** [comment]
Basically jbuilder always prefer the files in the source tree if they exist. This is useful for instance for  configuration files, that can be either generated by a configure script or from a default configuration for development.

I suppose we could mark explicitly the files for which we want this behavior.

**Comment by jnfoster** [comment]
I understand. I see how doing anything different might be tricky given jbuilder's choice to not require  the programmer to list out source files. Maybe there could be a mechanism for rules like `(menhir ...)` to somehow mark the `.{ml,mli}` files as generated and overwrite them or complain if they already exist?

**Comment by elfring** [comment]
How would you like to filter generated source files out from the other input files?
