### ISSUE TITLE
Jbuilder doesn't support 2 executables sharing a module

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#19]
E.g. something like:

```
(executables
 ((modules (x1 helper))
  (names (x1))))

(executables
 ((modules (x2 helper))
  (names (x2))))
```

It will complain that `helper` has multiple rules defined for it. This isn't a big deal because you can always just make `helper` a library but it would be good to either document if this is intended or lift this small limitation.

**Comment by diml** [comment]
This is intended, the two stanzas might build with a different configuration. Basically, the set of modules of two executables/library stanzas must never intersect

**Comment by rgrinberg** [comment]
Makes sense.
