### ISSUE TITLE
Compilation of jbuilder-1.0-beta10 fails on OCaml 4.02.3

### ISSUE THREAD

**Issue by lindig** [janestreet/jbuilder#192]
According to the README, OCaml 4.02.3 should be supported but compiling the tar ball fails:

```
: jbuilder-1.0-beta10 $ ocamlc -version
4.02.3
: jbuilder-1.0-beta10 $ make
./boot.exe -j 4 --dev
      ocamlc src/jbuilder__Watermarks.{cmi,cmti}
      ocamlc src/jbuilder__Cm_kind.{cmi,cmti}
      ocamlc src/jbuilder__Utils.{cmi,cmti} (exit 2)
(cd _build/default && /home/lindig/.opam/4.02.3/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I /home/lindig/.opam/4.02.3/lib/ocaml -I vendor/opam-file-format/src -I vendor/re/src -no-alias-deps -I src -open Jbuilder -o src/jbuilder__Utils.cmi -c -intf src/utils.mli)
File "src/utils.mli", line 25, characters 23-44:
Warning 50: unattached documentation comment (ignored)
File "src/utils.mli", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
Makefile:5: recipe for target 'default' failed
make: *** [default] Error 1
```

The problem is caused by this line:

```
: jbuilder-1.0-beta10 $ sed -n 25p src/utils.mli 
  -> ?in_the_tree:bool (** default: false *)
```

This works on the master branch - so it's save to close this. You might want to release a new tar ball, though.

**Comment by diml** [comment]
Hmm, it should work without the `--dev` argument, i.e. running these commands should be fine:

```ocaml
ocaml bootstrap.ml
./boot.exe -j 4
```

Usually people install jbuilder through opam, and the make invocation is more for developers. Maybe we could add a `make release` target.

**Comment by lindig** [comment]
My motivation was to build an OCaml project in the smallest setting possible: install OCaml, install jbuilder and compile the project. Usually I would also use Opam for this but this is in a context where I want to minimize dependencies.

**Comment by diml** [comment]
Ok, I added `make release` and updated the README. We are now testing the dev build with all supported versions of OCaml, so moving forward this problem shouldn't happen. However, it's probably safer to rely on release settings in general

**Comment by rgrinberg** [comment]
`$ make all-supported-ocaml-versions` confirms that 4.02.3 is supported. jbuilder definitely intends to support 4.02.3 so please don't hesitate issues like this.
