### ISSUE TITLE
Add warnings for common misuses of wrapped

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#194]
I see two common cases where wrapped is either wrongly omitted or misused:

* A library contains a single module but `(wrapped false)` isn't set.

* Users are prefixing all their module names with the library name in wrapped mode.

Both cases seem like errors in the majority of the time. Should we add a warning in jbuilder for this perhaps?

**Comment by diml** [comment]
I'm not sure it's worse making jbuilder complain about these. When you start a library, you might have only one module but still want you library wrapped in case you add more modules later. Similarly you might start with only a couple of modules starting with the same prefix, in which case the warning would be just noise and impossible to silence

**Comment by rgrinberg** [comment]
OK sure. Without a way to silence these, this probably won't work well.
