### ISSUE TITLE
Automatic generation of .merlin files

### ISSUE THREAD

**Issue by xguerin** [janestreet/jbuilder#203]
Is there a way to disable the generation of .merlin files ?

**Comment by dra27** [comment]
What's your motivation for doing that?

**Comment by xguerin** [comment]
Well, simply not wanting to have generated files in my source tree that I don't care about without resorting to adding them in my .gitignore. Especially since I am already maintaining my own .merlin file.

**Comment by diml** [comment]
We could also explore the possibility of merlin not reading .merlin files from the source directory. That would benefit more people.

BTW why are you maintaining your own .merlin file?

**Comment by xguerin** [comment]
> BTW why are you maintaining your own .merlin file?

I'm not sure I understand the question. Isn't that the legacy method ? Or there is a merlin file generator that has been around for a long time (pre-jbuilder) I am not aware of ?

I believe I simply followed the merlin documentation where the .merlin files is (by default) requested to be present in the root directory of the project.

On a side note, shouldn't I have the option to keep my merlin files and use jbuilder only as a builder ? Or is it expected that using jbuilder also means leaving to the tool the management of merlin files ?

**Comment by dra27** [comment]
@diml means why are you maintaining your own .merlin file now that you're using jbuilder.

jbuilder is opinionated, so it's not necessarily the case that there should be an option, but let's step back. Is there any important difference between your .merlin and the one(s) jbuilder is generating?

In principle, there shouldn't be anything in the .merlin file which is not already in jbuild files, hence the reason they are considered build artefacts by jbuilder. They're generated in the source tree because Merlin presently requires that, but it may be possible to alter Merlin either to read .merlin files from _build or even to have Merlin be able to interpret jbuild files directly (which would be much better, as Merlin would then never get a stale configuration because the .merlin files hadn't been rebuilt)

**Comment by xguerin** [comment]
> @diml means why are you maintaining your own .merlin file now that you're using jbuilder.

Legacy, I suppose ? I have a whole bunch of projects where I maintain my own .merlin for which I started considering using jbuilder. Hence the snags.

> jbuilder is opinionated, so it's not necessarily the case that there should be an option

It's perfectly fine to be opinionated. And after all, nobody forces me to use jbuilder. However, in my endeavor to use it I stumbled upon this quirk and referred to your documentation which does not mention this particular design choice.

To the contrary, the documentation is actually fairly verbose about how to *enable* merlin generation when defining new contexts. From there I simply inferred that there must be a way to parameterize that generation and posted my question.

> In principle, there shouldn't be anything in the .merlin file which is not already in jbuild files, hence the reason they are considered build artefacts by jbuilder.

It makes sense, and it's a nice feature to have.

But I'm a big fan of the unix philosophy and it seems to me that the automated generation of configuration files for a code checker tool should fall beyond the default scope of a build tool.

When left undocumented, it is counter-intuitive, it unnecessarily pollutes existing code hierarchies and it leads to annoying question from clueless would-be users like me.

**Comment by dra27** [comment]
The intention is that part of porting to use jbuilder means that you'll `git rm` (or whatever) all your .merlin files :smile:

The documentation mentions the generation of Merlin configuration in the third paragraph of the Overview, but it's clearly not prominent enough! Which section are you talking about for enabling Merlin file generation? The only other section I think is the `context` section in `jbuild-workspace` under Usage. That should probably be more explicit that if you have no jbuild-workspace file (so an implied `(context default)`) then you will get `.merlin` files. The only way to disable Merlin generation is to have explicit build contexts only.

The question isn't annoying - it reveals that we need to improve the docs. The pollution (I agree it's a shame - I like having everything in _build) can be dealt with by future improvements to Merlin.

In your case here, users would still be fine, but if we make Merlin generation an opt-in feature, then we can have repositories which do not include it by default, which is annoying for contributors to any project who sensibly use Merlin, even if the original authors do not!

**Comment by xguerin** [comment]
Thank you for the explanation.

> Which section are you talking about for enabling Merlin file generation? The only other section I think is the context section in jbuild-workspace under Usage

This is the one to which I was referring.

**Comment by rgrinberg** [comment]
There was another ticket that asked for a similar option and it was rejected. Just to summarize, we share the same displeasure with having these ugly .merlin files sprinkled everywhere. But jbuilder's workaround of at generating is at least better than doing it yourself. Let's hope that further improvements in merlin makes these files unnecessary.
