### ISSUE TITLE
Support custom ocamlfind predicates

### ISSUE THREAD

**Issue by jpdeplaix** [janestreet/jbuilder#208]
If we have a library with such a META file, there is no way to trigger the ```thisone``` predicate using jbuilder:
```
archive(byte,-thisone) = "default.cma"
archive(byte,thisone) = "good.cma"
```
Could you add a way to support custom ocamlfind predicates ?

**Comment by diml** [comment]
Supporting the full power of findlib predicates in jbuilder would be complicated. There is a discussion in #136 about supporting libraries with multiple implementations. I assume it would cover this case.

**Comment by jpdeplaix** [comment]
> Supporting the full power of findlib predicates in jbuilder would be complicated.

Can you elaborate ? Is there a reason not to use the ```Fl_metascanner``` from ```findlib``` for instance ? I understand that using ocamlfind (the binary) can be rather slow but is it also the case with its library ?

**Comment by diml** [comment]
The implementation is not the issue, jbuilder already has an implementation of a subset of findlib.

Jbuilder ensures that things work the same way whether the dependencies are installed or present in the workspace. This allows you to work on several related projects simultaneously and can cut down compilation times as well.

To keep this property and handle custom findlib predicates we'd need to teach jbuilder about these predicates, both when defining a library for which you'd write such a meta file if you were writing it by hand and at use sites. This seems complicated.

The idea in #136 or in the namespace proposal is to capture the most important use case of findlib predicates, which is to define several implementations for a given interface.

**Comment by rgrinberg** [comment]
Full support for OCaml predicates was also ruled in the dev meeting at the ICFP. So the odds of this being implemented are microscopic, therefore I will close this.

However, @jpdeplaix please continue to bring up other use cases of predicates that jbuilder fails to meet.
