### ISSUE TITLE
Multiple ppx preprocessors gives "Extension x was not translated" error

### ISSUE THREAD

**Issue by dakk** [janestreet/jbuilder#213]
I'm trying to use multiple preprocessors on my jbuild file like following (https://github.com/dakk/bitcoinml/blob/master/src/jbuild):

```sexp
(preprocess (pps (ppx_bitstring ppx_sexp_conv)))))
```
but when I try to compile compile I got this error:

```
Command [5] exited with code 1:
$ (cd _build/default && ./.ppx/ppx_bitstring+ppx_sexp_conv/ppx.exe --dump-ast --cookie 'library-name="bitcoinml"' -o src/tx.pp.ml --impl src/tx.ml)
File "src/tx.ml", line 22, characters 45-54:
Error: Extension `bitstring' was not translated
```
Note that when I try to compile the project only with ppx_bitstring it compiles well, but it returns the error when I add ppx_sexp_conv.

I don't know if this is a jbuild issue.

**Comment by diml** [comment]
I don't think it's a jbuilder issue. Can you try adding `-no-check`?

```
(preprocess (pps (ppx_bitstring ppx_sexp_conv -no-check)))))
```

**Comment by dakk** [comment]
No check solved the problem.. So I can close this issue?

**Comment by diml** [comment]
Yh, it's a ppx_driver issue

**Comment by dakk** [comment]
Ok thanks for the clarification
