### ISSUE TITLE
Unexpected executing halt

### ISSUE THREAD

**Issue by tryggvigy** [janestreet/jbuilder#214]
I'm fiddling around with reasonml and ocaml core.

### Problem
![image](https://user-images.githubusercontent.com/2373958/29004637-3ea6e894-7acb-11e7-8ff8-83cde1fa6bd4.png)
But the output should be:
```
I print
I don't
```
It seems like `open Async.Std;` halts executing some how.

I tried to find related issues but found nothing. 
This looks like a issue but maybe I am missing something trivial?

### Source files
<details>
    <summary><code>jbuild</code></summary><p>

```
(jbuild_version 1)

(executable
 ((name main)
  (libraries (core async))
  (preprocess (pps (ppx_jane)))
 ))
```

  </p></details>

<details>
    <summary><code>main.re</code></summary><p>

```ocaml
open Core.Std;
print_endline "I print";
open Async.Std;
print_endline "I don't";
```

  </p></details>

**Comment by anemator** [comment]
I don't think this is a jbuilder issue. Try calling `never_returns (Scheduler.go ())` at the end of the file. You can use Control-C to exit when it blocks.

From [RealWorldOCaml:](https://realworldocaml.org/v1/en/html/concurrent-programming-with-async.html)
> One of the most common newbie errors with Async is to forget to run the scheduler. It can be a bewildering mistake, because without the scheduler, your program won't do anything at all; even calls to printf won't reach the terminal.

**Comment by tryggvigy** [comment]
Aha! Thanks @anemator. This was my issue

**Comment by anemator** [comment]
You're welcome.

**Comment by dra27** [comment]
Do head over to our [Discourse forum](https://discuss.ocaml.org) if you need any more help :smile:
