### ISSUE TITLE
Print directory changes

### ISSUE THREAD

**Issue by Chris00** [janestreet/jbuilder#223]
Jbuilder should (maybe with a flag `-w`) print directory changes, outputting a line like:
```
jbuilder: Entering directory '<dir>'
```
where `<dir>` is the target directory (possibly given relatively to the current one).  This is needed so that the error links work when compilation takes place under Emacs.  Example: with a command like `jbuilder build -j 4 --root=..` a line `jbuilder: Entering directory '..'` should be printed.

**Comment by dra27** [comment]
Related to (perhaps duplicate of?) #138

**Comment by Chris00** [comment]
Yes, it is a duplicate.
