### ISSUE TITLE
jbuilder exec : pass hyphenated flags?

### ISSUE THREAD

**Issue by rdavison** [janestreet/jbuilder#225]
I'm trying to run `jbuilder exec app.exe -H` but whenever I do so jbuilder thinks the -H is one of its own flags... But oddly enough, if it isn't hyphenated it seems to get passed into the invoked app.exe just fine.  Am I doing something wrong? Could someone confirm this behavior? I couldn't find any documentation that covers this case.

**Comment by hcarty** [comment]
I'm not sure if it's documented, but you can use `--` to separate jbuilder arguments from your program's arguments. For example:

```
jbuilder exec myapp -- --flag-for-my-app
```

**Comment by dra27** [comment]
`--` is fairly standard (`xargs`, etc.) but we should make that explicit in the docs, as it's something one often needs.

**Comment by rdavison** [comment]
Wizards!  Thank you.  I will rename the issue to suggest adding documentation for this feature.
