### ISSUE TITLE
incorrect `S _` directives in the generated .merlin when copying source files from other directories

### ISSUE THREAD

**Issue by jvillard** [janestreet/jbuilder#229]
For instance, [here's the jbuild](https://gist.github.com/jvillard/8e0aae6df9aac622bce84ccc246812eb) generated by [infer's jbuild file](https://github.com/facebook/infer/blob/b1b7cc0b9ddd24e3aa9d4220495d36da1a42c591/infer/src/jbuild.in). The [generated .merlin](https://gist.github.com/jvillard/1ad15cb613e3bdbdcf320c416acc54dd) contains the following source directives:

```
S .
S atd
S istd
```

Most source files are in subdirectories and merlin will not find them with this configuration. The directories listed here are those that have their own jbuild files.

I would have expected the following directives, listing all the directories where source files have been copied from as well:

```
S .
S absint
S backend
S base
S bufferoverrun
S checkers
S clang
S eradicate
S harness
S integration
S IR
S java
S labs
S quandary
S scripts
S unit
S unit/clang
S atd
S istd
```

Note that paths to files to copy are absolute in my paste, but the same .merlin with the same issue is generated if I change them to be relative paths instead.

**Comment by diml** [comment]
I supposed we could adjust the generation of merlin files. However it seems to me that #35 is the right solution to this problem. There has been some back and forth on #35 but in the end we should end-up with something like this:

```scheme
(library
 (...
  (import_dirs (unit quandary labs ...))))
```

**Comment by diml** [comment]
Closing this as #35 has been merged.
