### ISSUE TITLE
Give a proper warning when having a duplicate public_name

### ISSUE THREAD

**Issue by SanderSpies** [janestreet/jbuilder#244]
This message was a bit confusing to me:
```
Multiple rules generated for _build/default/_doc/ocaml-webworker/index.html
```
Apparently I had two libraries with a public_name that caused this.

It would be nice if jbuilder would give a better error message for this.

**Comment by diml** [comment]
Agreed, it should be easy to add a check [here](https://github.com/janestreet/jbuilder/blob/a7067f5aa867c4c0d21650491e03793caf734f52/src/lib_db.ml#L126)
