### ISSUE TITLE
the maintainer of libsvm is trying to move to jbuilder, he needs some help

### ISSUE THREAD

**Issue by UnixJunkie** [janestreet/jbuilder#248]
There are C stubs and the test target is no more working under jbuilder:
Cf. https://bitbucket.org/ogu/libsvm-ocaml/issues/3/update-files-generated-from-_oasis
Thanks for any help.
I'm not a jbuilder expert yet so I am not very helpful.

**Comment by rgrinberg** [comment]
This has been addressed on bitbucket. In the future, you can ask such general questions discuss.ocaml.org, there are many users of jbuilder that could have helped with this that don't follow the bug tracker.
