### ISSUE TITLE
Incorrect generated .merlin?

### ISSUE THREAD

**Issue by pveber** [janestreet/jbuilder#249]
On the following [gist](https://gist.github.com/pveber/dcb47fadccdc0d7d771a6cdfd387d345), compilation with `jbuilder` works great but `merlin` is unhappy with syntax extensions. If I change in `.merlin` the line:
```
FLG -ppx '/home/pveber/tmp/delme/_build/default/.ppx/ppx_sexp_conv/ppx.exe --as-ppx --cookie '\''library-name="delme"'\'''
```
by
```
FLG -ppx '/home/pveber/tmp/delme/_build/default/.ppx/ppx_sexp_conv/ppx.exe --as-ppx'
```
It works fine again. Any idea what's wrong here?

**Comment by diml** [comment]
It should work if you use the latest version of merlin and jbuilder

**Comment by pveber** [comment]
Precisely, I'm already using `master` branch of both tools:
```
[booker:~/w 19:41]$opam pin
jbuilder.1.0+beta12                  git   https://github.com/janestreet/jbuilder.git                                
merlin.3.0.2                         git   https://github.com/ocaml/merlin.git                                       
```
Would you know if there is some log I can check?

**Comment by rdavison** [comment]
If you're using vim, perhaps you could try calling :MerlinErrorCheck to get some information?  I don't know how to do it with emacs.

**Comment by pveber** [comment]
Thanks Richard, unfortunately I'm too ignorant on vi to do that easily. If this is the only way I guess I'll give it a try.

**Comment by diml** [comment]
I don't really know how things should be quoted inside `.merlin` files. /cc @let-def, @trefis. Now that these files are machine generated, it might be easier to just use marshal...

**Comment by pveber** [comment]
Ok, nevermind: reinstalling everything from a clean switch made the problem disappear. Sorry for the noise!
