### ISSUE TITLE
quickstart example does not work

### ISSUE THREAD

**Issue by vzaliva** [janestreet/jbuilder#251]
Trying the very first exampe from [Quick Start](https://jbuilder.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program) document fails with:

```
Error: The current scope defines no packages.
What do you want me to do with this (install ...) stanzas?.
You need to add a <package>.opam file at the root of your project so that
I know that you want to install things as part of package <package>.
```

**Comment by dra27** [comment]
You've either copied the example incorrectly or you're running it in a directory containing other things. The only way you could get that message would be by adding a `public_name` field to the `jbuild` file or by trying this example in a directory with other unrelated files.

**Comment by vzaliva** [comment]
Very strange. I think I was copying it verbatim. Sorry for a false alarm.
