### ISSUE TITLE
Simple compilation (of complex code) broken by "-inft-suffix .ml"

### ISSUE THREAD

**Issue by jacquev6** [janestreet/jbuilder#254]
Hello,

Abstract: passing `-intf-suffix .ml` to `ocamlopt` breaks compilation in some cases.

Details:

The code in [`test.ml`](https://gist.github.com/jacquev6/4dce7ee500785176d200fe942e701257#file-test-ml) doesn't compile *to native* with jbuilder. Here is the output of `jbuilder build test.exe`:

        ocamldep test.depends.ocamldep-output
          ocamlc test.{cmi,cmo,cmt}
        ocamlopt test.{cmx,o} (exit 2)
    (cd _build/default && /home/vincent/.opam/rdas-4.05.0+flambda/bin/ocamlopt.opt -w -40 -g -intf-suffix .ml -no-alias-deps -I . -o test.cmx -c -impl test.ml)
    File "test.ml", line 1:
    Error: The implementation test.ml does not match the interface test.cmi:
           Values do not match:
             val g : ([< `Poly of 'b M'.t & 'a M'.t ] as 'a) -> int
           is not included in
             val g : ([< `Poly of 'b M'.t & 'a M'.t ] as 'a) -> int
           File "test.ml", line 13, characters 8-9: Actual declaration

Note that the error is quite weird: the expected and actual types for `val g` are identical.

If I remove the `-intf-suffix .ml` flags and run `(cd _build/default && /home/vincent/.opam/rdas-4.05.0+flambda/bin/ocamlopt.opt -w -40 -g -no-alias-deps -I . -o test.cmx -c -impl test.ml)` manually, it compiles OK.

The code itself is rather complex: it contains a module alias, a recursive function, and uses a dynamic variant to make a recursive type from a parametric type, and I think all are needed to exhibit the issue.
But compiling it is simple: it is self-contained and can actually be compiled by `ocamlopt test.ml`.

The `runme.sh` script and the `jbuild` file in the same gists can be used to reproduce the issue.

Questions:
- what is the purpose of `-intf-suffix .ml`?
- could it be added only when it's required?
- could it be removed entirely?

Thanks!

**Comment by xclerc** [comment]
After further investigation, it appears that it is not a jbuilder issue but
a compiler one. Do you want to report the issue, or do you prefer me
to do so?

As a workaround, @lpw25 suggested to add an annotation to `g`:
````
let rec g : 'a . ([< `Poly of 'a M'.t ] as 'a) -> int = fun expr ->
````

**Comment by jacquev6** [comment]
Wow, I've found a bug in the OCaml compiler! Thanks for the investigation, I'll repackage the gist to demo the bug outside of jbuilder and submit a new ticket in the OCaml Mantis.

For my curiosity, and as this seems to trigger the compiler bug, can you please tell me a bit about using `-intf--suffix .ml`? It feels weird to tell the compiler to use `.ml` files as interface files. Or maybe I'm misunderstanding the doc in `ocamlc --help`: `-intf-suffix <string>  Suffix for interface files (default: .mli)`.

**Comment by xclerc** [comment]
Also, answers to your questions:

- `-intf-suffix .ml` is used to tell the compiler that the file extension for interfaces is `.ml` (it is `.mli` by default);
- it is added by `jbuilder` only when required: it is a trick used when there is no `.mli` file ; the module is compiled by `ocamlc` to get a `cmi` and then the switch tricks `ocamlopt` into thinking that there is actually an interface file that produced the `cmi` file (if you don't do that, `ocamlopt` will try to produce a `cmi` file, just like `ocamlc`, and it can result in a race condition during parallel builds);
- `jbuilder` will generate a compilation command with no `-intf-suffix` switch if you have an `mli` file.

Hope this helps.

**Comment by jacquev6** [comment]
Awesome, thanks! I'll report to the OCaml Mantis today or tomorrow.

**Comment by jacquev6** [comment]
I've just opened https://caml.inria.fr/mantis/view.php?id=7629

**Comment by xclerc** [comment]
Great; thanks!
