### ISSUE TITLE
Library of a single cmo.

### ISSUE THREAD

**Issue by pveber** [janestreet/jbuilder#261]
I have quite a peculiar use case where I need a library to be made of a single `cmo` not wrapped in a `cma`. The intention here is that I have a lib `foo.a` that performs a side-effect (initialization) required by `foo.b`, but there is no actual call from the latter to the former. By setting an `ocamlfind` dep between `foo.b` and `foo.a`, and if `foo.a` is a `cmo`, then I have the guarantee  `foo.a` will be loaded before starting to load `foo.b`.

Hence my question: is it possible to specify a library consisting of a single `cmo`, not wrapped inside a `cma`? I suspect the answer is no, since the use case is very specific (and maybe debatable), but just in case... Thanks!

**Comment by diml** [comment]
If you add `(library_flags (-linkall))` to `foo.a`, don't you get the same behavior as if `foo.a` was a single cmo?

**Comment by pveber** [comment]
Well it does seem to work. Thanks a ton!
