### ISSUE TITLE
Menhir rule doesn't work in some case

### ISSUE THREAD

**Issue by hackwaly** [janestreet/jbuilder#264]
Seems `*.mly` files must at the same level of `_build` directory?

![image](https://user-images.githubusercontent.com/540298/30768762-b811ff30-9fd2-11e7-87aa-9bf3c5d17506.png)

src/jbuild file:
```
(jbuild_version 1)

(executable
 ((name main)))

(menhir
 ((merge_into parser)
  (modules (tokens parser))))

```

error message:
```
jbuilder build src/main.exe
      menhir src/parser.{ml,mli} (exit 1)
(cd _build/default && /Users/wenyuxiang/.opam/4.05.0/bin/menhir --base parser tokens.mly parser.mly)
Error: parser.mly: No such file or directory
```

@rgrinberg

**Comment by hackwaly** [comment]
Sorry, I didn't see https://github.com/janestreet/jbuilder/pull/258

**Comment by diml** [comment]
Actually it was a different bug. It's not fixed
