### ISSUE TITLE
Error: no packages are defined here

### ISSUE THREAD

**Issue by alinpopa** [janestreet/jbuilder#27]
I was trying to come up with some very little project that shows, hopefully, how to use jbuilder, because at least for me it's a bit mystical; that project is here: https://github.com/alinpopa/jbuilder_example01

Trying to build it using the bellow command, and I'm getting the following error, which doesn't really make too much sense to me:

```
jbuilder build --debug-actions --debug-dependency-path --debug-rules --debug-findlib @install

Workspace root: /Users/alin/work/ocaml/jbuilder_example01
File "bin/jbuild", line 1, characters 0-0:
Error: no packages are defined here
```
I believe that I'm trying to find out what's the magical incantation to build a proper project, with some minimalistic structure, only very few modules, etc. I'd think that having an example project, more than a very simple one liner hello world, would help a bit with starting working with jbuilder (at least this would help me, but I wasn't able to find a proper simple project, without using a mix of opam/make/merlin files, which confuses me a lot).
Sorry, I'd have raise this as a question on some mailinglist/slack channel/something, but turns out that there is no such communication channel? For example, a JaneStreet OCaml mailing list, or anything... is this mailing list something I could use for such a topic? https://groups.google.com/forum/#!forum/ocaml-core

Thanks.

**Comment by rgrinberg** [comment]
I've created a pull request to your project fixing up your project and giving you some tips. This should be enough for a "hello world" starter. I'm curious, did you find the information in https://github.com/janestreet/jbuilder/blob/master/doc/quick-start.org useful? It seems like a pretty complete tutorial.

As for examples, I'd look at other janestreet packages. These aren't hello world level, but should be useful to you eventually.

Regarding communication channels. #ocaml on freenode is pretty accessible to ask quick questions.

**Comment by alinpopa** [comment]
The quickstart doesn't really show how a proper project layout should look like, so I tried looking at other janestree's projects, but again, due to my lack on knowledge in this area, was a bit difficult to understand what's happening, so I went with some quick and dirty trial and error approaches, that got me to this point. Your PR works just fine, and also the extra clarifications you added regarding the opam files were quite helpful; thank you.

**Comment by diml** [comment]
Following this ticket, I added an `example` directory with a complete project example. I also explained in the README why many projects have a toplevel Makefile

**Comment by alinpopa** [comment]
Oh, that's very nice; thank you.
