### ISSUE TITLE
jbuilder clean specific folder

### ISSUE THREAD

**Issue by rdavison** [janestreet/jbuilder#270]
Currently `jbuilder clean` cleans the entire project, but perhaps we should allow it to accept a path argument so it only cleans things within a specific subtree.

example:
`jbuilder clean .`
`jbuilder clean src`

**Comment by rgrinberg** [comment]
Is there a concrete use case for this? I think more motivation is necessary to implement this.

**Comment by rgrinberg** [comment]
Closing as there's not enough motivation given. Please re-open if you have some convincing use cases.
