### ISSUE TITLE
Feature Request: builds without .opam files

### ISSUE THREAD

**Issue by vzaliva** [janestreet/jbuilder#273]
Sometimes I need to build executables which will be later installed manually, not via OPAM. For example sometimes it is done as part of docker container build.

Currently, I do not see a way to use jbuilder on such projects as it complains about missing .opam file. 

```
Error: The current scope defines no packages.
What do you want me to do with this (install ...) stanzas?.
You need to add a <package>.opam file at the root of your project so that
I know that you want to install things as part of package <package>.
```

Please consider allowing to perform build even when .opam file is missing.

**Comment by dra27** [comment]
Jbuilder's definitions for installation are based around opam package names, but you don't have to use opam (or even opam-installer) to install them. You can either avoid having a `public_name` field completely in your `executable` stanza (often less convenient, as it means you have to call `jbuilder build foo.exe`) and pick up the artefact however you wish from `_build/default/foo.exe` or you can have an empty *package*.opam file and run `jbuilder build @install` and pick it up along with anything else from `_build/install/default/bin/foo.exe` (or you can parse the generated .install file - it can also be read using the opam-file-format library).

The mechanism for specifying that is not something which will change.
