### ISSUE TITLE
Merlin source directive missing for executables

### ISSUE THREAD

**Issue by copy** [janestreet/jbuilder#276]
For example,

```
(jbuild_version 1)
(executable
  ((name test)))
```

generates this `.merlin`:

```
B _build/default
FLG -w -40
```

**Comment by rgrinberg** [comment]
This does not seem to be specific to executables. The same source directive is absent in .merlin files defined for libraries as well. What problems does this create? Does it break merlin in some situations?

**Comment by copy** [comment]
It breaks the `list-modules` command (for example completion of the `:ML` command).

**Comment by rgrinberg** [comment]
`S .` will be added to every .merlin from now on.
