### ISSUE TITLE
Add an atdgen stanza

### ISSUE THREAD

**Issue by brendanlong** [janestreet/jbuilder#295]
We have a jbuild file in a project that uses a bunch of atdgen files:

```
(jbuild_version 1)

(library
 ((name orca)
  (wrapped false)
  (libraries (atdgen base_ cohttp.async nocrypto email_message inifiles xml-light yojson ezxmlm))
  (preprocess (pps (ppx_jane ppx_driver.runner)))))

(rule
 ((targets (cloudsearch_payloads_j.ml cloudsearch_payloads_j.mli))
  (deps    (cloudsearch_payloads.atd))
  (action  (run atdgen -j -j-std ${^}))))

(rule
 ((targets (cloudsearch_payloads_t.ml cloudsearch_payloads_t.mli))
  (deps    (cloudsearch_payloads.atd))
  (action  (run atdgen -t -j-std ${^}))))

(rule
 ((targets (instance_metadata_payloads_j.ml instance_metadata_payloads_j.mli))
  (deps    (instance_metadata_payloads.atd))
  (action  (run atdgen -j -j-std ${^}))))

(rule
 ((targets (instance_metadata_payloads_t.ml instance_metadata_payloads_t.mli))
  (deps    (instance_metadata_payloads.atd))
  (action  (run atdgen -t -j-std ${^}))))

(rule
 ((targets (orca_sqs_payloads_j.ml orca_sqs_payloads_j.mli))
  (deps    (orca_sqs_payloads.atd))
  (action  (run atdgen -j -j-std ${^}))))

(rule
 ((targets (orca_sqs_payloads_t.ml orca_sqs_payloads_t.mli))
  (deps    (orca_sqs_payloads.atd))
  (action  (run atdgen -t -j-std ${^}))))

(rule
 ((targets (payloads_j.ml payloads_j.mli))
  (deps    (payloads.atd))
  (action  (run atdgen -j -j-std ${^}))))

(rule
 ((targets (payloads_t.ml payloads_t.mli))
  (deps    (payloads.atd))
  (action  (run atdgen -t -j-std ${^}))))

(rule
 ((targets (s3_list_response_j.ml s3_list_response_j.mli))
  (deps    (s3_list_response.atd))
  (action  (run atdgen -j -j-std ${^}))))

(rule
 ((targets (s3_list_response_t.ml s3_list_response_t.mli))
  (deps    (s3_list_response.atd))
  (action  (run atdgen -t -j-std ${^}))))
```

It would be really nice if we could write that as:

```
(jbuild_version 1)

(library
 ((name orca)
  (wrapped false)
  (libraries (atdgen base_ cohttp.async nocrypto email_message inifiles xml-light yojson ezxmlm))
  (preprocess (pps (ppx_jane ppx_driver.runner)))))

(atdgen
 (cloudsearch_payloads.atd instance_metadata_payloads.atd orca_sqs_payloads.atd payloads.atd s3_list_response.atd))
```

It seems like atdgen is pretty common, so I think it would be worth having something like this built into jbuilder.

I could probably write this, but I wanted to make sure that this is something you would accept, and that there's not some other way of doing this that we're missing (besides making all of our jbuild files into OCaml programs.. ugh).

**Comment by brendanlong** [comment]
(I guess for general-purpose usage, there should also be some way to specify `-j` and `-t`)

**Comment by rgrinberg** [comment]
It's very unlikely that direct support for this would be merged. First of all, it would really make more sense to add support for wildcard patterns. Which will reduce boilerplate in this case and others like it. But also, at the ICFP, Jeremie unveiled the extension mechanism planned for jbuilder. This mechanism could also be used to cut down on boilerplate like this.

I think support for wildcard patterns would still be accepted however. But it's a bit tricky to implement.

**Comment by rgrinberg** [comment]
I'm closing this as we won't have builtin atdgen rules and there's already a ticket for wildcard patterns.

**Comment by brendanlong** [comment]
@rgrinberg What's the ticket for wildcard patterns? I looked through the open issues and couldn't find it (and a search for "wild" or "wilcard" didn't find anything either).

**Comment by rgrinberg** [comment]
https://github.com/janestreet/jbuilder/issues/53

But looks like it's closed. I will create a proper issue and link the appropriate comments.
