### ISSUE TITLE
Can't handle submodules with public libraries?

### ISSUE THREAD

**Issue by brendanlong** [janestreet/jbuilder#297]
I'm trying to build a repo like this:

 - module_that_depends_on_x
    - src
        - module_that_depends_on_x.ml
        - jbuild
 - module_that_depends_on_x.opam
 - x
    - x.opam
    - src
        - x.ml
        - jbuild

And I get an error:

```
File "x/src/jbuild", line 5, characters 2-19:
Error: The current scope doesn't define package "x".
The only packages for which you can declare elements to be installed in this directory are:
- module_that_depends_on_x (because of module_that_depends_on_x.opam)
```

Isn't jbuilder supposed to let me nest modules like this? We have a module we want to open source, and we don't want to have to manually comment this out every time we sync with the public version (and I think this makes git submodules and subtrees impossible?).

Note: I see that jbuilder itself deals with this by commenting out `public_name` in the vendored `re`: https://github.com/janestreet/jbuilder/blob/master/vendor/re/src/jbuild

It seems like the correct behavior here is that if jbuilder sees `public_name`, it should look for $name.opam in every folder above the current one until it finds one, like it does in a lot of other cases.

**Comment by brendanlong** [comment]
(And again, I can try to implement this if you agree that it's a worthwhile improvement)

**Comment by rgrinberg** [comment]
jbuilder avoids a public_name for its vendored re because it does not want this package to be installed.

Does x/src/jbuild contain a library with a `public_name` `x`? It shoudl because you have an `x.opam` file.

**Comment by brendanlong** [comment]
Ohhh.. our issue is that linked vendor/x to x, so jbuilder is essentially correctly being confused that x/src/jbuild defines `public_name` when x.opam doesn't exist (even though vendor/x/x.opam does exist). What we're doing here is a hackish in-transition thing (so our OMake build will keep working for now), so I think the solution is to just also link vendor/x/x.opam to x.opam.

Sorry about the non-bug report :\
