### ISSUE TITLE
Support "!" in variables such as ${!CC}

### ISSUE THREAD

**Issue by Chris00** [janestreet/jbuilder#300]
I'd like to compile a C program that must be installed alongside a library that binds to it.  To that effect, I wrote the rule
```
(rule
 ((targets (p.exe))
  (deps    (p.c))
  (action  (run ${!CC} -o p.exe p.c -lm))))
```
but it does not work because `${CC}` contains flags which are considered part of the program name — and `!` does not split the components.  Would it be possible the make `!` work as for other variables?

**Comment by dra27** [comment]
I'm for this too - I'm hitting it in the related case of invoking bytecode images of the compiler (so where you're running `ocamlrun /path/to/ocaml/boot/ocamlc`)
