### ISSUE TITLE
AppVeyor: test with 4.05 & 4.06

### ISSUE THREAD

**Issue by Chris00** [janestreet/jbuilder#324]
Prebuilt OCaml 4.05 and 4.06 are [available for testing with AppVeyor](https://github.com/Chris00/ocaml-appveyor/releases).  You may want to [upgrade](https://github.com/Chris00/ocaml-appveyor) your scripts using a [matrix](https://github.com/Chris00/root1d/blob/master/appveyor.yml).

**Comment by dra27** [comment]
Thanks for the ping on this - I've updated the AppVeyor scripts to build using 4.06.0.

For now, I think it's OK that we test the matrix of compiler versions using Travis and, although I'm willing to be argued down, I don't think there's a benefit to testing the same version matrix in AppVeyor too. What I would like to move towards testing is the six Windows ports of the latest version as an AppVeyor build matrix - but that's for another day!

**Comment by Chris00** [comment]
Well, with the new releases the quoting bug shows — not with the older ones! :-)

@dra27 Would you like I give you commit access to https://github.com/Chris00/ocaml-appveyor ?  That way, the development of this can benefit all projects and not solely jbuilder.

**Comment by dra27** [comment]
Sorry, I'm being slow about which new releases you're referring to? Don't go adding commit access for me for now - but it is most certainly my intention at some point to contribute AppVeyor ideas back upstream - I don't know at the moment when I'm going to get to it, though!

**Comment by Chris00** [comment]
Sorry, I meant with the OCaml builds for 4.05 and 4.06, the problem with the space in the compiler popped up.
