### ISSUE TITLE
Escape quotes in META files

### ISSUE THREAD

**Issue by Chris00** [janestreet/jbuilder#331]
A META file generated from the following synopsis
```
  (synopsis  "Ropes (\"heavyweight strings\")")
```
reads
```
description = "Ropes ("heavyweight strings")"
...
```
where the fact that the inner quotes are not escaped is problematic with ocamlfind.

**Comment by rgrinberg** [comment]
Thanks Christophe. Do you plan on making a patch for this issue?

**Comment by Chris00** [comment]
On 2017-11-16, Rudi Grinberg wrote:
> 
> Thanks Christophe. Do you plan on making a patch for this issue?

I can try take a look later — but don’t hold your breath!
