### ISSUE TITLE
jbuilder runtest prevents running tests again

### ISSUE THREAD

**Issue by vietlq** [janestreet/jbuilder#387]
I'm following the guide at https://jbuilder.readthedocs.io/en/latest/quick-start.html#defining-tests :

```
(jbuild_version 1)

(alias
 ((name    runtest)
  (deps    (my-test-program.exe))
  (action  (run ${<}))))
```

This allows me to run `jbuilder runtest` only once. How can I run again and again without changing any file?

Thanks.

**Comment by rgrinberg** [comment]
master has an option `--force` to do this. You will have to pin jbuilder or wait for a new release unfortunately.

**Comment by vietlq** [comment]
Thanks @rgrinberg ! Happy New Year!
