### ISSUE TITLE
Building intermediate targets

### ISSUE THREAD

**Issue by mmottl** [janestreet/jbuilder#395]
How can I build e.g. `.cmo` files that are part of a library directly from the command line?  I want to force `jbuilder` (well, soon to be `dune`)  to build certain intermediate targets first.  Sometimes several parts of a system may be incomplete, but I want to work on a particular file and not clobber the terminal with error messages coming from parts I'm not focusing on.  If I try e.g. the following in my `src` directory:

```
jbuilder build foo.cmo
```

I get:
```
Don't know how to build src/foo.cmo
Hint: did you mean src/foo.ml?
```

**Comment by rdavison** [comment]
Can you do `jbuilder build src/foo.cmo`?

**Comment by mmottl** [comment]
No, then I get:

```
Don't know how to build src/src/foo.cmo
```

The system is apparently aware of the correct directory to search.

**Comment by rgrinberg** [comment]
if you do something like `$ jbuilde rules -m -r` you will see all the .cmo targets available to you.

**Comment by mmottl** [comment]
@rgrinberg The command failed, because it requires an installation of `js_of_ocaml`.  Not sure whether one could easily eliminate this dependency.

After installing `js_of_ocaml`, the `rules` command now works and shows that one has to not only provide the full path to the `build` directory, but also prefix the intermediate targets with the containing library.  E.g. when executing inside the `src` directory:

```
jbuilder build ../_build/default/src/mylib__Foo.cmo
```

I don't think that's something a beginner would want to figure out.  Maybe some path conversion magic could be used to make this a little easier.  `jbuilder build mylib.cma` is already possible so some more convenience targets shouldn't be too difficult to support.

**Comment by hhugo** [comment]
You should be able to just run `jbuilder build src/mylib__Foo.cmo` - no need to refer to `_build/default`

**Comment by mmottl** [comment]
It seems that a typo in the name prevented me from finding the shortest solution.  Not even `src` is required, only the library prefix (including two underscores): `jbuilder build mylib__Foo.cmo`
