### ISSUE TITLE
"key "CAML_LD_LIBRARY_PATH" present multiple times"

### ISSUE THREAD

**Issue by Drup** [janestreet/jbuilder#46]
Not sure if it's an opam 2 bug or a jbuilder one. cc @AltGr

When I use the workspace feature (after doing ``eval `opam config env --switch 4.03.0` ``) I get:
```
Running[1]: /usr/bin/opam config env --root /home/gabriel/.opam --switch 4.04.0 --sexp > /tmp/jbuild5f4db6.output
File "", line 1, characters 0-796:
Error: key "CAML_LD_LIBRARY_PATH" present multiple times
```

And indeed, the relevant piece of the opam output is:
```
  ("CAML_LD_LIBRARY_PATH" "/home/gabriel/.opam/4.04.0/lib/stublibs")
  ("CAML_LD_LIBRARY_PATH" "/home/gabriel/.opam/4.04.0/lib/ocaml/stublibs:/home/gabriel/.opam/4.04.0/lib/ocaml")
  ("CAML_LD_LIBRARY_PATH" "/home/gabriel/.opam/4.04.0/lib/stublibs:/home/gabriel/.opam/4.04.0/lib/ocaml/stublibs:/home/gabriel/.opam/4.04.0/lib/ocaml")
```

I'm not sure which of opam or jbuilder should be made more resilient here. I would guess both. :p

**Comment by diml** [comment]
I think jbuilder could provide a better error message, but it should still be an error. This looks like a configuration problem somewhere and shouldn't be ignored

**Comment by Drup** [comment]
Why? Those are env variables, so behaves like they do: take the last one. Opam regularly duplicate env variables in my shell when I switch locally, and that's okay. Everything still works fine.

**Comment by diml** [comment]
I suppose. Well, if this is considered a bug in opam, jbuilder can be changed to consider only the last binding and output a warning. If it's not a bug, then jbuilder can silently take the last binding.

**Comment by diml** [comment]
I changed the behavior to printing a warning and taking the last binding
