### ISSUE TITLE
Testing a ppx define in jbuilder

### ISSUE THREAD

**Issue by Drup** [janestreet/jbuilder#48]
I would like to test a ppx that I build with jbuilder. I tried several approaches
- The oldschool method : 
   ```
   ocaml -noinit -noprompt -ppx my_ppx < test.ml 2>&1 | tail -n +19 > test.result
   diff test.expected test.result
   ```
   Problem: I can't figure out how to talk about `my_ppx`.
- The compiler/jsoo method: inline `expect_test` in my project and use it on my test file
  Problem: Still can't figure out how to talk about the `my_ppx` executable, and not sure how to actually run `expect_test` with it.
- The "new" method, with `toplevel_expect_test`
  Problem: Regardless of the fact that the packaging is so badly done that I can't even actually run it. I have no idea how to actually write the build rules for the toplevel that interact with my ppx.

So, what's the solution ? I would really like to be *at least* able to write the rules for the first (old school) method.

**Comment by diml** [comment]
For the first method, if your ppx uses omp, you can simply build a custom driver:

ppx.ml:
```ocaml
Migrate_parsetree.Driver.run_as_ppx_rewriter  ()
```

jbuild:
```scheme
(executable
 ((name ppx)
  (libraries (my_ppx ocaml-migrate-parsetree))))

(rule
 ((targets (text.result))
  (deps     (test.ml))
  (action   (system "${OCAML} -noinit -noprompt -ppx ${exe:ppx.exe} < ${<} 2>&1 | tail -n +19 > ${@}"))))
```

For the last method, `toplevel_expect_test` run the rewriters in-process. So you can build a custom `ocaml-expect` and link it with `my_ppx`. However, currently  this only works for `ppx_driver` based rewriters. I'm planning to make this work with all omp based rewriters at some point, but it's not done yet.

**Comment by Drup** [comment]
Thanks, this is helpful! The oldschool method will do for now, until the `expect` story is a bit better fleshed out.

**Comment by diml** [comment]
I'm closing this issues as I think there is nothing more to do from the point of view of jbuilder
