### ISSUE TITLE
Can't build jbuilder

### ISSUE THREAD

**Issue by arkdae** [janestreet/jbuilder#59]
First off, I'd like to apologize in advance if this is not the proper location for this. I can not find any information on how to install jbuilder, nor can I find any information on a mailing list or some means to contact the project community regarding my problems trying to install this software.

I see there is a Makefile, so I type make:
ocaml bootstrap.ml
File "bootstrap.ml", line 11, characters 5-8:
Error: Syntax error
make: *** [boot.exe] Error 2

I can only assume that my version of ocaml is old. I'm trying to install jbuilder on CentOS 7 (as is necessary for some other software).
> rpm -qa | grep ocaml
ocaml-4.01.0-22.7.el7_2.x86_64
ocaml-runtime-4.01.0-22.7.el7_2.x86_64
ocaml-findlib-1.3.3-6.el7.x86_64
ocaml-compiler-libs-4.01.0-22.7.el7_2.x86_64

**Comment by bmillwood** [comment]
Looks like (according to the jbuilder.opam file) you need at least 4.02.3.

**Comment by rgrinberg** [comment]
And to get a newer ocaml it's recommend to install [opam](http://opam.ocaml.org/). Once you have opam setup, getting jbuilder will only require `$ opam install jbuilder`
