### ISSUE TITLE
How to use sedlex?

### ISSUE THREAD

**Issue by bikalgurung** [janestreet/jbuilder#68]
Hi,
I am trying to build a project that uses sedlex for lexing tokens. I have  `(preprocess (pps (sedlex)))` in my jbuild file. However, I keep getting `uninterpreted extension %sedlex.regexp?`. Am I specifying the sedlex ppx incorrectly?

**Comment by adrieng** [comment]
Hi,

Sedlex is at the moment not compatible with jbuilder, since the latter by design does not handle old-style syntax extensions that are not based on migrate-parse-tree or ppx_driver.

One possible solution is to use the PR alainfrisch/sedlex#47 (currently in limbo) which ports Sedlex to ocaml-migrate-parsetree. It can then be used easily with jbuilder.

**Comment by bikalgurung** [comment]
@adrieng ah, that makes sense. Thanks for the response.

**Comment by bikalgurung** [comment]
@adrieng I pinned your branch of sedlex (with ocaml-migrate-parsetree) but am getting the same error 
`Error: Uninterpreted extension 'sedlex.regexp'.` My `jbuild` is as follows,

```
(library
  ((name          hello1) 
   (public_name   hello1)  
   (libraries   (menhirLib sedlex batteries))
   (preprocess (pps (sedlex)))))
```
Am I something missing?

Alternately, I tried with `ppx_driver.runner` as follows,
```
(library
  ((name          hello1) 
   (public_name   hello1)  
   (libraries   (menhirLib sedlex batteries))
   (preprocess (pps (sedlex ppx_driver.runner)))))
```
But I am still getting an error,
`Error: Extension `sedlex.regexp' was not translated`

Not sure what I am doing wrong or missing here. Any ideas?

**Comment by adrieng** [comment]
Have you tried "sedlex.ppx"? I have successfully used the patched sedlex together with jbuilder with "(preprocess (per_file ((pps (sedlex.ppx)) (file_using_sedlex))))" in the jbuild file.

**Comment by bikalgurung** [comment]
@adrieng yep this worked. `(preprocess (pps (sedlex.ppx)))`. Not sure I understand why it worked but thanks.

**Comment by adrieng** [comment]
@bikalgurung As far as I remember, the issue is just that Sedlex exposes its syntax extension as the sedlex.ppx subpackage in its META file.

**Comment by vkurchatkin** [comment]
@adrieng for some reason I still get `Error: Extension `sedlex.regexp' was not translated`, even with `sedlex.ppx`

**Comment by adrieng** [comment]
@vkurchatkin which version of sedlex are you using? Can you post the relevant part of your jbuild file?

**Comment by vkurchatkin** [comment]
Sedlex version 1.99.4, jbuild config:

```
(executable
  (
     (name hello_world)
     (preprocess (pps (sedlex ppx_driver.runner)))
     (libraries (sedlex))
  )
)
```

**Comment by vkurchatkin** [comment]
@adrieng oops, sorry about that, it seems that just `sedlex.ppx` works, but `sedlex.ppx ppx_driver.runner` doesn't. The problem is that I want to use more than one ppx, but i.e. `(ppx_jane sedlex.ppx)` doesn't work as well

**Comment by adrieng** [comment]
@vkurchatkin I'll investigate this when I have more time. In the meantime you could perhaps organize your code so that your lexer module doesn't use other syntax extensions, and then use jbuilder's `per_module` settings. But I agree that this is not a satisfactory solution.

**Comment by diml** [comment]
`(pps (sedlex.ppx ppx_driver.runner -no-check))` should work. If you use `ppx_driver.runner`, all the rewriters should be based on `ppx_core`. `ppx_driver.runner` enables additional safety checks to make sure all attributes have been interpreted, but this only works for rewriters based on `ppx_core`. In general you just shouldn't use `ppx_driver.runner`, I'm not sure why it doesn't work without
