### ISSUE TITLE
Use local switch by default

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#71]
opam 2.0 introduced a cool new feature: local switches[1]. These are very useful for project specific sandboxes. Would it be possible for jbuilder to support these local switches? I'm thinking of jbuilder defaulting to the project local switch rather than the current switch for example.

[1] https://www.ocamlpro.com/2017/04/27/new-opam-features-local-switches/

**Comment by diml** [comment]
If i read the post correctly, as long as the user calls `eval $(opam config env)`, this is what will happen. What would you do differently?

**Comment by rgrinberg** [comment]
I think jbuilder should consider giving the local switch a higher priority
than the current switch. I.e without having the user set the env vars as
you said.

My motivation is to simplify the workflow with project sandboxes. I know I
can already accomplish this by writing workspace files. But it seems like
unnecessary boilerplate when I really want the same behavior in every case.

**Comment by diml** [comment]
Well, unless you have workspaces configured by a `jbuild-workspace` file, jbuilder doesn't use opam at all. I think it's a good default. Implicitly using a different environment by default mightl lead to confusing problems for users, especially ones new to ocaml/opam.

You can already select a different default with:

```sh
$ alias jbuilder="jbuilder --workspace=$HOME/.jbuild-workspace"
```

However, you still have to write an explicit switch name in the workspace file. We could simply make the `(switch ...)` field optional so that it is selected automatically.

**Comment by rgrinberg** [comment]
> Implicitly using a different environment by default mightl lead to confusing problems for users, especially ones new to ocaml/opam.

I disagree with this. I think most users are accustomed to installing dependencies inside sandboxes that are isolated from other projects. See how npm, cargo, stack, etc. all work. While I witnessed many new users being confused by opam's share by default model. Furthermore, it's hard to imagine a new user creating a local switch and being confused by its existence.

> However, you still have to write an explicit switch name in the workspace file. We could simply make the (switch ...) field optional so that it is selected automatically.

If that makes it so that I can use the local opam switch without any configuration I think that's a good compromise. Happy to make that happen if so.

**Comment by diml** [comment]
I think it'd be weird if jbuilder behaves in a certain way but running commands directly does something different.

> If that makes it so that I can use the local opam switch without any configuration I think that's a good compromise. Happy to make that happen if so.

You need to change the `switch` argument of `Context.create_for_opam` to an optional one. Then you need to make the `Context.Kind.Opam.switch` and `Workspace.Context.Opam.switch` field options.

**Comment by diml** [comment]
Here is another idea:

```sh
$ export PROMPT_COMMAND='eval $(opam config env)'
```

then changing switch becomes as simple as changing directory and it will affect all tools, not just jbuilder.

**Comment by rgrinberg** [comment]
It's not good enough unfortunately. Here's a motivating use case:

I'm working on 2 different projects that have their own switches within one emacs instance. I'd like to switch working on these projects from inside my editor without this manual dance of changing the environment. I understand that I can accomplish this with clever use of emacs. But not everybody knows how to extend their editors, and there are many editors that are popular now.

**Comment by diml** [comment]
OK, well I don't mind having this as a command line option, that would solve the editor problem

**Comment by rgrinberg** [comment]
Actually, I'm not sure if what I've proposed is at all the correct approach. For the simple reason that doing

```
$ opam exec jbuilder build
```

already accomplishes exactly what I'm talking about. However, there's one small and unrelated problem: jbuilder seems to recognize the `jbuild` files from the downloaded sources in the `_opam` directory. Could we add the `_opam` directory to the list of paths jbuilder doesn't descend into by default?

**Comment by diml** [comment]
yes, we should do that indeed

**Comment by diml** [comment]
Is there still something to do for this issue or can it be closed?
