### ISSUE TITLE
How to add support for capnp code generation?

### ISSUE THREAD

**Issue by talex5** [janestreet/jbuilder#73]
I wanted to tell jbuilder how to build OCaml files from capnp schema files. I tried:

```
 ((targets (%.ml %.mli))
  (deps (%.capnp))
  (action (run capnpc -o ocaml ${<}))))
```

But it seems that doesn't work. It would be good to say something about this in the manual (even if it's that it isn't possible).

**Comment by diml** [comment]
I added a note in the manual. You can do it currently but you need to setup one rule per .capnp file

**Comment by samoht** [comment]
@talex5 I have some basic runes there: https://github.com/linuxkit/linuxkit/blob/master/projects/miragesdk/src/sdk/jbuild#L11-L18

**Comment by talex5** [comment]
@samoht: I've made a PR on capnp itself so you don't need the stuff about disabling warnings any more: https://github.com/pelzlpj/capnp-ocaml/pull/13

**Comment by diml** [comment]
I'm assuming there is nothing more to do here, so I'm closing this issue
