### ISSUE TITLE
Use with opam-cross-windows

### ISSUE THREAD

**Issue by hcarty** [janestreet/jbuilder#75]
Is it possible to use jbuilder with https://github.com/whitequark/opam-cross-windows?  I tried a hackish approach of putting the `$SWITCH/windows-sysroot/bin` at the front of my `$PATH` but that gives me an error stating that `ocamlyacc` isn't available at the same path.

I see that jbuilder is expecting all `ocaml*` executables to live in the same directort.  I don't see a simple way to work around this.  Any suggestions?

Thank you!

**Comment by diml** [comment]
It'd be nice if it worked. Making sure that the various ocaml tools comes from the same place is a way a making sure we are not picking up ocamlc from one installation and ocamlopt from another. However, `ocamlyacc` and `ocamllex` could probably be treated as normal tools. I don't mind changing this.

Currently jbuilder looks for these binaries in the same directory as where it found `ocamlc`:
- `ocaml`
- `ocamlc`
- `ocamlopt`
- `ocamllex`
- `ocamlyacc`
- `ocamldep`
- `ocamlmklib`

Can you send the result of `which <bin>` for all of these?

**Comment by diml** [comment]
In fact jbuilder was looking for `ocamllex`/`ocamlyacc` at the same place as `ocamlc` when discovering the environment, but then it was doing nothing with them, so I just stopped looking for them eagerly

**Comment by hcarty** [comment]
Thank you! Apologies for not replying sooner.
