### ISSUE TITLE
Latest version of ppx_deriving not working with jbuilder

### ISSUE THREAD

**Issue by bikalgurung** [janestreet/jbuilder#76]
Hi,
I have pinned the latest version of https://github.com/whitequark/ppx_deriving which implements migrate_parsetree based ppx. However, using `(preprocess (pps (ppx_deriving.std)))` doesn't seem to apply any ppx_deriving based transformations. Is my usage not correct? If so could you please provide guidance of how we can use ppx_deriving with jbuilder.  

I opened an issue is ppx_deriving but I got directed here instead. 
https://github.com/whitequark/ppx_deriving/issues/134#issuecomment-300956742

**Comment by diml** [comment]
The problem is that currently ppx_deriving doesn't register itself with the ocaml-migrate-parsetree driver
 and jbuilder only supports ppx through the ocaml-migrate-parsetree driver. 

I replied on the original ticket.
