### ISSUE TITLE
Menhir support and documentation

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#8]
Menhir is quite common as an alternative to ocamlyacc. Ideally, it shouldn't be any harder to use than ocamlyacc.

**Comment by diml** [comment]
Agreed

**Comment by diml** [comment]
Note that `(ocamlyacc ...)` is now desugared in jbuild_types.ml, so it should be straightforward to add menhir support

**Comment by rgrinberg** [comment]
I had a brief look at this today. There's a couple of non trivial differences to account for here:

* menhir wants to run ocamldep to do some dependency analysis.
* menhir supports defining a parser across multiple .mly files (the equivalent of .mlypack in ocamlbuild).

The 2nd point I imagine can be handled by passing in multiple module names to a menhir stanza. But I'm not sure how to handle the 1st point.

**Comment by diml** [comment]
Do you know if calling ocamldep is mandatory? I.e. can menhir be used to generate only the .ml/.mli files and leave the rest to the build system? I didn't know menhir was calling ocamldep, but curious to know if it's just for helping people using makefiles or if menhir does something with the dependency analysis.

Agreed for the second point. I quickly checked the manual and it seems that you indeed need to pass all the files at once to menhir.

**Comment by rgrinberg** [comment]
I asked on the menhir mailing list and this is the reply I got:

https://sympa.inria.fr/sympa/arc/menhir/2017-03/msg00004.html

Seems like the answer is that it's not essential for basic support. But to fully support menhir it will be necessary.

**Comment by diml** [comment]
I see. There are quite a few things that would need to be changed in order to be able to do that. Especially, currently it is assumed that the various code generators (such as ppx rewriters or other generators) don't need to run the typer. As a result jbuilder calls ocamldep once per library/executable stanza after having generated/pre-processed all the .ml/.mli files

**Comment by rgrinberg** [comment]
What we have is good enough for now.
