### ISSUE TITLE
Creating a simple per-project workflow

### ISSUE THREAD

**Issue by hcarty** [janestreet/jbuilder#94]
jbuilder already provides a very nice workflow per-project.  How possible would something like the following be?

The basic idea is to use opam switches to setup per-OCaml-version shared tools (merlin, ocp-index/ocp-browser, ocp-indent) with project-local builds for everything else (base/astring/angstrom/etc).

For example, a user would have a `4.04.1+flambda` switch available with its own `merlin`, `ocp-indent` and other project-generic tooling.

Then a user would clone or create a project (let's call it Project A (PA)) they are working on.  This project would use `jbuilder` as its build system and include appropriate `*.opam` files specifying dependencies.

A `jbuilder init-vendor` or `jbuilder init-deps` command could be available which would pull down the source code for all of PA's transitive dependencies, unpacking them under a local directory `_vendor` (or some other appropriate name).  This `_vendor` directory could live within a switch-specific context.  `opam` could/would be used to determine the appropriate dependencies to pull down.  All of the depedencies would either use `jbuilder` as their build system or have appropriate `jbuild` configurations in their source tree to enable this approach.

`jbuilder` would know to include `_vendor` in the directories it crawls while looking for things to build.  It would also, I think, ignore any libraries which are installed in a switch-global context since all of the required libraries should be available under `_vendor`.  This could help avoid conflicts between tool dependencies and project dependencies.

If I understand how `jbuilder` works correctly, this should allow each project to have their own local, unique set of dependent libraries available without having to duplicate compilers and build tools per-project.

**Comment by hcarty** [comment]
Also @altgr as I'm not sure if the source retrieval and unpacking makes more sense in jbuilder or opam.

**Comment by lpw25** [comment]
What would this provide over using [opam's local switches](https://opam.ocaml.org/blog/opam-local-switches/)?

**Comment by hcarty** [comment]
The primary benefit would be saving build time of the compiler and development​ tools since they could be shared between projects.

A potential benefit is avoiding dependency conflicts between dev tools (merlin, ocp-indent, etc) and a project.

**Comment by lpw25** [comment]
I think that saving the build time would be better addressed in opam. I know @AltGr is interested in a Nix-style build cache, and I think that would give you a cleaner solution.

I'm not sure I follow the other point. I would expect you to install your development tools in a global switch and arrange your editor to use the tools from that switch. So I don't see why they would be conflicting with your local switch.

**Comment by hcarty** [comment]
I see this as a sort of middle ground between the proposed `vendor` command (#43) and full support for relocation/caching in opam.  I think the tooling exists to provide this or something close to it, with a bit of scaffolding to support automatically grabbing and unpacking all of the source code to an appropriate subdirectory.

If caching in opam is coming soon, maybe a more useful target (again, possibly belonging in opam) would to cloning the dev repos of all of the dependencies of a project in a similar `_vendor`-like directory.

For sharing development tools - thank you for suggesting that.  I honestly hadn't considered that approach.  Would you create a `dev-tools-4.04.1` switch and use explicit paths to its `merlin` and `ocp-indent` in your editor configuration, letting opam setup the rest of the environment for compilation?  If that is the recommended approach to using opam it would be good to document it somewhere.

**Comment by rgrinberg** [comment]
The questions raised here are very valid but are likely to be addressed in opam itself or the upcoming bob tool. Jbuilder's purpose is to only be a build tool, and since the scaffolding proposed here can be implemented just as easily outside the tool. I think that's where it should really be pursued.

@hcarty I think this would raise a much more lively discussion on the discuss forums :)
